# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=128)),
                ('Address', models.CharField(max_length=1024)),
                ('CreditScore', models.IntegerField(verbose_name=4)),
            ],
        ),
        migrations.CreateModel(
            name='loadboard_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin', models.CharField(max_length=128)),
                ('Destination', models.CharField(max_length=128)),
                ('Email', models.CharField(max_length=256)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadboard.company_table')),
            ],
        ),
    ]
