# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_table',
            name='companylogo',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='loadboard_table',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadboard.Company_table'),
        ),
    ]
