# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadboard', '0003_auto_20161217_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadboard_table',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadboard.Company_table'),
        ),
    ]
