# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadboard', '0005_auto_20161224_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_table',
            old_name='Company',
            new_name='CompanyName',
        ),
        migrations.RemoveField(
            model_name='loadboard_table',
            name='Favourite',
        ),
        migrations.AlterField(
            model_name='loadboard_table',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadboard.Company_table'),
        ),
    ]
