# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loadboard', '0006_auto_20170304_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadboard_table',
            old_name='Company',
            new_name='CompanyId',
        ),
        migrations.AlterField(
            model_name='loadboard_table',
            name='CompanyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loadboard.Company_table'),
        ),
    ]
